django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("fileapp.urls")),
    path("dropbox/", include("dropbox.urls")),
]

dropbox/urls.py
from django.urls import path
from .views import (
    TaskFileListView,
    FileDetailView,
    RunScriptView,
    DownloadView,
)

app_name = 'dropbox'

urlpatterns = [
    # testing this url logic 
    path('file/', TaskFileListView.as_view(), name='task_file_list'),
    path('file/detail/', FileDetailView.as_view(), name='file_detail'),
    path('file/detail/run/', RunScriptView.as_view(), name='run_script'),
    path('file/detail/download/', DownloadView.as_view(), name='download'),
]

'''urls for classes with <int:file_id> set up'''
# path('file/', TaskFileListView.as_view(), name='task_file_list'),
    # path('file/<int:file_id>/', FileDetailView.as_view(), name='file_detail'),
    # path('file/<int:file_id>/run/', RunScriptView.as_view(), name='run_script'),
    # path('file/<int:file_id>/download/', DownloadView.as_view(), name='download'),


'''urls for functions'''
    # path('file/', views.task_file_list, name='task_file_list'),
    # path('file/<int:file_id>/', views.file_detail, name='file_detail'),
    # path('file/<int:file_id>/run/', views.run_script, name='run_script'),
    # path('file/<int:file_id>/download/', views.download, name='download'),

fileapp/urls.py
from django.urls import path
from . import views

app_name = 'fileapp'

urlpatterns = [
    path('upload/', views.upload, name='upload'),
    path('download/', views.download, name='download'),
]

templates/old/download.html
<a href="{% url 'dropbox:upload' %}">Back to Upload File</a>

{% if file %}
    <h2>Download File</h2>
    <a href="{% url 'dropbox:download' file.id %}" download>Download CSV</a>
{% else %}
    <h2>No file uploaded yet</h2>
{% endif %}

templates/old/run_script.html
{% extends "base.html" %}

{% block content %}
<h2>run_script html</h2>

<div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl m-3">
    <div class="md:flex">
        <div class="p-8">
            <div class="run-python-code">
                <!-- Display file upload form -->
                <form method="post" enctype="multipart/form-data" action="{% url 'dropbox:run_script' file_id=file.id %}">
                    {% csrf_token %}
                    <label for="file">Upload CSV File:</label>
                    <input type="file" name="file" id="file" required>
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" type="submit">Upload & Run Python Script</button>
                </form>
            </div>
            <!-- If file is provided, display download link -->
            {% if file %}
            <div class="file-detail mt-6">
                <h2 class="text-xl font-bold">{{ file.name }}</h2>
                <a href="{% url 'dropbox:download' file.id %}" class="text-blue-500">Download</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}

templates/old/success.html
{% extends 'base.html' %}

{% block content %}
<h3>Success</h3>
<p>Download file below</p>
<a href="{% url 'dropbox:file_detail' file_id %}">Success</a>


{% block content %}

templates/old/upload.html
<!-- create html form to upload file -->

{% extends 'base.html' %}

{% block content %}
<h2>Upload File</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>
{% endblock content %}

```

templates/old/xfilelist.html
<!-- create html from xfilelist method in views.py listing all files in the xfile table of the database -->

html
{% extends 'base.html' %}

{% block content %}
<h2>Files</h2>
<table>
    <tr>
        <th>File Name</th>
        <th>Download</th>
    </tr>
    {% for file in files %}
    <tr>
        <td>{{ file.name }}</td>
        <td><a href="{% url 'dropbox:download' file.id %}" download>Download</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock content %}

<!-- 
 -->